### ISSUE TITLE
sea-orm entity usage gives me error

### ISSUE THREAD

**Issue by hongkongkiwi** [JosephLenton/serde-email#1]
When using with sea-orm 0.11.1 I get this:
```
6  | #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Deserialize, Serialize)]
   |                                       ^^^^^^^^^^^^^^^^^ the trait `From<Email>` is not implemented for `sea_orm::Value`
```

Using it like this:
```
use sea_orm::{ entity::prelude::*, ActiveValue::Set };
use serde::{Deserialize, Serialize};
use serde_email::Email;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Deserialize, Serialize)]
#[sea_orm(table_name = "user_emails", schema_name = "public")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  // #[serde(skip_deserializing)]
  pub id: Uuid,
  pub email_address: Email,
}
```

Any ideas?

**Comment by markcatley** [comment]
Are you sure you enabled the sea-orm feature in your Cargo.toml?

**Comment by JosephLenton** [comment]
Hey @hongkongkiwi , that error can happen if the version of Sea Orm you are using in your local project is a different version to that used in `serde_email`.

I released a new version of `serde_email` yesterday which is updated to the latest version of Sea Orm. If you update to the latest versions on your own project (for Serde Email and Sea Orm), then you should find this works. (At the time of writing the latest version of Sea Orm is 0.11.3).
